[package]
name = "loki-bms-client"
version = "0.1.0"
authors = ["OrbitusII <dlodholm@icloud.com>"]
edition = "2018"

[dependencies]
iced                = { version = "0.3", features = ["canvas"]}
loki-bms-common     = { path = "../common" }